<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Law Pavillion Test </h1>



    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="<?= $this->url("application", ["action" => "repopulate"]) ?>" >
        Re-populate Database
    </a>

    <a class="btn btn-primary btn-lg" href="<?= $this->url("application", ["action" => "export"]) ?>">
       Export Files &raquo;
    </a>
</div>